[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "c131f492b9cc45076e60abf27ce57a18d673aa36"
os = "macos"

    [[p7zip.download]]
    sha256 = "2772d4575cadf075ba5a6fc7ff4f9932c795258bdc95998a1d12eb658619cfd5"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.aarch64-apple-darwin.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "52ab8fd85f1ea552c08e7639a7293eed9ee5b233"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "d0d1eaff6cc357ab494dddff26f2a0731d644579f8733e0761a056f1c8f39fa9"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.aarch64-linux-gnu.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "f8e1b12ff5e5bbe2050f45cdf62b09d668b7a070"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "89aa58b81699f84c63c35d2465bbfb40a5a84bbfc48d96d1228f8166cba2cd04"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.aarch64-linux-musl.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "ab7da63aaaec051b49133eb4da685d4ce1fa900e"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "5c443fc1539edadd4928bbccd0e91c6eebad8ef4c65424dd38947c405b7266dd"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.aarch64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7050bbe566c89a278a864e429e42fb8270f39cf9"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "8fccde6e392557a043b8754f16f4bbabed30c30da91226e02ded604a3a9f4b07"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.armv6l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62cf8006d07455952e66112437e2afc15a97383b"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "d7eb0a32a9aed323bbe10ca773c2005d1952dd057012a819e095941cbb81faa6"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.armv6l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "519db0e44254e629e3ba8eec8679201bf2b17f72"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "c4108e0cf83c492d60ace7436b4939e7705555042a1407864eb9344e697f806f"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.armv7l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d59422a0f71136c0189e79b82e8d37da02841451"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "31b60633c7d8792c601355081322e14b1425700455ee6665fa267fcf75562e8f"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.armv7l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "a239da6932514889fd498e45ef18034d3ddbc55a"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "03cd0b088e0ec85532af8bff4130e29a7d09cd8fe68e6c0ffdeb92bb28c52573"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.i686-linux-gnu.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "bb81502d323fdff91cd69f561a5bedf13e41f34a"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "db7dc5d27b3aa9a21be5b41bdddd73db87a7e2303077cf25d479000ee8d3bd7a"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.i686-linux-musl.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "c781f139d2c9e8b2b65664f77351d5a567139d86"
os = "windows"

    [[p7zip.download]]
    sha256 = "19e5ab263cb005948b734433631c25e72317433ed9211c776cf0db415565b490"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.i686-w64-mingw32.tar.gz"
[[p7zip]]
arch = "powerpc64le"
git-tree-sha1 = "d6ed986851e92f5e6cd4ab31856583d5e9c73a6b"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "a8c9dbb5fb744cdd37b8bdef85c3e902eb356debf9f5c582f65e03739d91344c"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.powerpc64le-linux-gnu.tar.gz"
[[p7zip]]
arch = "riscv64"
git-tree-sha1 = "149b45be46f22cc8720e1cb55b4470a61e1f8a56"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "d6faf5cac6912a250d8aeced7bcf5145fb023dfc970d5223221efef324de12e2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.riscv64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "4ba5b713b0454212232ba7f3e5a6a71178e7823a"
os = "macos"

    [[p7zip.download]]
    sha256 = "b7d41aefe720e065b620c9d2025d59f5e8bd78dde19881a1f448437608f18730"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-apple-darwin.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "66bec8a898bd8840ae7bdb7950ef7cb01d503215"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "fe587ecc0d87f47f352a43bb0519a0ffef5ffdda3697f969f3bcf7737be9a967"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "39bc5bf1f4182478189121f6e2340cd8f52bfdc4"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[p7zip.download]]
    sha256 = "feda7ef15a5b84cc9dd3bbb4b22d4620ecf2c3869e7bd52e89efac5290369e98"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "13db7f3815feb2319120012ee515512d70820086"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "8af7b6f1a014bac8cdf06d2c35564824d6f03ee8d5d49feead00f8a1e2de58d6"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-linux-musl.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "ff37c1bb41cd448674a9f46e7f2be7307aa0b10f"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "0e8c502d76145710908384cb1062dc8b75db44f2d20a93c65a45a2c908ed4a61"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "61c91e25b04a391a639c057b757db29b9e1e5236"
os = "windows"

    [[p7zip.download]]
    sha256 = "f3bce2adc16db4c8799c2ad286de0033640c453b9a148c0dfcf53bcca4ce5ab0"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.6.1+0/p7zip.v17.6.1.x86_64-w64-mingw32.tar.gz"
